name: notebook-environment
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - pip=23.0.1
  - numpy=1.23.5
  - pandas=1.5.3
  - geopandas=0.12.2
  - rasterio=1.3.6
  - matplotlib=3.7.1
  - pip:
      - tensorflow==2.12.0
      - Pillow==9.5.0
