name: notebook-environment
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - numpy=1.23.5
  - pandas=1.5.3
  - geopandas=0.12.2
  - rasterio=1.3.6
  - matplotlib=3.7.1
  - ast
  - os
  - random
  - tensorflow=2.12.0
  - Pillow=9.5.0
  - io